version: '3.9'
services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: durka
      POSTGRES_DB: Order-processing-and-monitoring-system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: api-server
    depends_on:
      - kafka
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:durka@postgres:5432/Order-processing-and-monitoring-system?sslmode=disable
      - KAFKA_BROKERS=kafka:9092

  order-adder:
    build:
      context: ./order-adder
      dockerfile: Dockerfile
    container_name: order-adder
    depends_on:
      - kafka
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:durka@postgres:5432/Order-processing-and-monitoring-system?sslmode=disable
      - KAFKA_BROKERS=kafka:9092

  order-status-changer:
    build:
      context: ./order-status-changer
      dockerfile: Dockerfile
    container_name: order-status-changer
    depends_on:
      - kafka
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:durka@postgres:5432/Order-processing-and-monitoring-system?sslmode=disable
      - KAFKA_BROKERS=kafka:9092

volumes:
  postgres_data:
