database:
  user: "postgres"
  password: "durka"
  dbname: "Order-processing-and-monitoring-system"
  port: "5432"
  host: "postgres"
  sslmode: "disable"

kafka:
  brokers: "kafka:9092"
server:
  port: ":2222"